name: korani
description: Quran Application.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  assets_audio_player: ^3.1.1
  flutter_animate: ^4.5.2
  fluttertoast: ^8.2.10
  font_awesome_flutter: ^10.8.0
  hive: ^2.2.3
  path_provider: ^2.1.5
  quran: ^1.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
